//
//Commands//
//
var rats = ["LOOK AT RATS", "INVESTIGATE RATS", "SEARCH", "RATS", "RAT"];
var help = ["HELP", "BACK", "SEARCH", "HINT"];
var sleep = ["GO TO SLEEP", "SLEEP", "USE BED", "REST"];
var dresserInt = ["LOOK IN DRESSER", "LOOK AT DRESSER", "IN DRESSER", "GO IN DRESSER", "OPEN DRESSER", "GO TO DRESSER", "WALK TO DRESSER", "USE DRESSER", "OPEN DRAWER"];
var bedCommands =  ["WALK TO BED", "GO BED", "BED", "LOOK AT BED", "LOOK BED", "GO TO BED", "HEAD TO BED", "USE BED", "LAY DOWN", "LAY ON BED"];
var closetCommands =  ["WALK TO CLOSET", "CLOSET", "GO CLOSET", "LOOK AT CLOSET", "LOOK CLOSET", "GO TO CLOSET", "USE CLOSET"];
var closetInterior = ["LOOK IN CLOSET", "OPEN CLOSET", "GO IN CLOSET"];
var closetButton = ["USE CLOSET BUTTON", "TOUCH BUTTON", "PUSH BUTTON", "LICK BUTTON", "SMASH BUTTON", "PRESS BUTTON", "PRESS", "USE BUTTON", "PRESS CLOSET BUTTON", "PRESS BUTTONS", "TOUCH BUTTONS", "USE BUTTONS", "PUSH BUTTONS", "LICK BUTTONS", "SMASH BUTTONS", "PRESS BUTTONS"];
var dresserCommands =  ["WALK TO DRESSER", "LOOK AT DRESSER", "DRESSER", "GO TO DRESSER", "LOOK DRESSER", "USE DRESSER", "CHANGE CLOTHES", "OPEN DRESSER"];
var windowCommands =  ["WALK TO WINDOW", "WINDOW", "GO WINDOW", "LOOK AT WINDOW","WALK TO PORTHOLE", "PORTHOLE", "GO PORTHOLE", "LOOK AT PORT HOLE", "PORT HOLE", "GO PORT HOLE", "LOOK AT PORT HOLE", "WALK TO PORT HOLE", "WINDOWS", "VISIT WINDOW", "LOOK OUT WINDOW", "VIEW WINDOW", "VIEW PORTHOLE", "VIEW PORT HOLE"];
var hitWindow = ["HIT WINDOW", "SMASH WINDOW", "BREAK WINDOW", "KICK WINDOW", "PRESS WINDOW", "HIT PORTHOLE"];
var doorCommands =  ["WALK TO DOOR", "GO DOOR", "DOOR", "LOOK AT DOOR", "USE DOOR", "GO TO DOOR", "OPEN DOOR", "PUSH DOOR", "LEAVE"];
var deskCommands =  ["WALK TO DESK", "DESK", "GO DESK", "LOOK AT DESK", "LOOK DESK", "VISIT DESK", "GO TO DESK", "SIT AT DESK", "USE DESK"];
var screenCommands =  ["LOOK AT TABLET", "TAKE TABLET", "USE TABLET", "PICK UP TABLET", "GET TABLET", "READ TABLET", "LOOK AT CAPTAIN'S LOG", "LOOK AT CAPTAINS LOG", "READ"];
var stageTwoWakeUp = ["WAKE UP"];
var neck = ["CHECK NECK", "TOUCH NECK", "NECK", "LOOK AT NECK", "FEEL NECK", "EXAMINE WOUND", "TOUCH INJURY", "INJURY"]
var medKitCommands =  ["OPEN KIT", "LOOK AT KIT", "USE KIT", "MEDKIT", "USE MEDICAL KIT", "MEDICAL KIT", "LOOK AT MEDICAL KIT", "OPEN MEDKIT", "TAKE MEDKIT", "TAKE MEDICAL KIT", "GRAB MEDICAL KIT", "GRAB MEDKIT", "LOOK IN KIT", "LOOK IN MEDICAL KIT"];
var useSyringeStage = ["USE SYRINGE"];
var pickUpSyringe = ["PICK UP SYRINGE", "TAKE SYRINGE", "TAKE", "GRAB SYRINGE", "GRAB" ];
var vent = ["WALK TO VENT", "LOOK AT VENT", "VENT", "LOOK VENT", "LOOK AT FLOOR", "SEARCH FLOOR"];
var openVent = ["OPEN VENT"];
var wakeUp = ["WAKE UP", "GET UP"]
var kill = ["KILL ALIEN", "KILL", "FIGHT", "FIGHT ALIEN", "ATTACK", "ATTACK ALIEN", "KICK", "KICK ALIEN"];
var killWith = ["KILL WITH SYRINGE", "USE SYRINGE ON ALIEN", "USE SYRINGE ALIEN", "KILL ALIEN", "KILL"];
var run = ["RUN", "RUN AWAY", "HIDE"];
var bedCommands5Turn1 =  ["WALK TO BED", "GO BED", "BED", "LOOK AT BED", "LOOK BED", "GO TO BED"];
var bedCommands5Turn2 =  ["WALK TO BED", "GO BED", "BED", "LOOK AT BED", "LOOK BED", "GO TO BED"];
//
// End of commands //
//
